[2024-03-19T15:16:04.276+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipe.extract_product_id manual__2024-03-19T15:15:44.977278+00:00 [queued]>
[2024-03-19T15:16:04.294+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipe.extract_product_id manual__2024-03-19T15:15:44.977278+00:00 [queued]>
[2024-03-19T15:16:04.298+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-19T15:16:04.318+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_product_id> on 2024-03-19 15:15:44.977278+00:00
[2024-03-19T15:16:04.395+0000] {standard_task_runner.py:60} INFO - Started process 6086 to run task
[2024-03-19T15:16:04.492+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_pipe', 'extract_product_id', 'manual__2024-03-19T15:15:44.977278+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmptfznpgy7']
[2024-03-19T15:16:04.501+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask extract_product_id
[2024-03-19T15:16:05.318+0000] {task_command.py:423} INFO - Running <TaskInstance: data_pipe.extract_product_id manual__2024-03-19T15:15:44.977278+00:00 [running]> on host 4acc31316ec9
[2024-03-19T15:16:06.621+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='maihoangson180602@gmail.com' AIRFLOW_CTX_DAG_OWNER='Hoang Son' AIRFLOW_CTX_DAG_ID='data_pipe' AIRFLOW_CTX_TASK_ID='extract_product_id' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T15:15:44.977278+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-19T15:15:44.977278+00:00'
[2024-03-19T15:16:06.663+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: main() missing 1 required positional argument: 'args'
[2024-03-19T15:16:06.752+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=data_pipe, task_id=extract_product_id, execution_date=20240319T151544, start_date=20240319T151604, end_date=20240319T151606
[2024-03-19T15:16:06.910+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task extract_product_id (main() missing 1 required positional argument: 'args'; 6086)
[2024-03-19T15:16:07.056+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-19T15:16:07.180+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
